services:
  - type: web
    name: cnn-sentiment-api
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
