services:
  - type: web
    name: Subgrade_1
    runtime: node
    repo: https://github.com/braida/Subgrade_1
    plan: free
    region: frankfurt
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
version: "1"
